name: Create Pull Request

on:
  push:
    branches-ignore:
      - main

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          title: "PR for ${{ github.ref_name }}"
          draft: false
